#define PORT_COMPRESSOR 0

#define PORT_SOLENOID_A 0
#define PORT_SOLENOID_B 0

#define PORT_OPERATOR_CONTROLLER 0

#define ARM_FORWARD_BUTTON 0
#define ARM_REVERSE_BUTTON 0
#define ARM_STOP_BUTTON 0

